name: imechano
description: A Car Service Flutter App.
# Remove this line if you wish to publish to pub.dev
publish_to: "none"
# Version
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.2"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  # intl_translation:

  cupertino_icons: ^1.0.2
  get: ^4.5.1
  animations: 2.0.1
  flutter_native_screenshot: ^1.1.2
  google_translate: 0.0.5
  open_file: ^3.1.0
  swipe: ^0.0.1
  pdf: ^3.0.0
  badges: ^2.0.3
  flutter_markdown: 0.6.1
  flutter_screenutil: 5.0.4
  accordion: ^2.3.0
  google_maps_flutter:
  steps_indicator: ^1.3.0
  persistent_bottom_nav_bar: ^4.0.2
  expansion_tile_card: ^2.0.0
  modal_bottom_sheet: ^2.0.1
  flutter_otp_text_field: ^1.0.0
  dotted_border: ^2.0.0+2
  flutter_rating_bar: ^4.0.0
  date_picker_timeline: ^1.2.3
  http:
  rxdart:
  url_launcher: any
  shared_preferences: ^2.0.11
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.5
  google_api_headers: ^1.1.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  hive: ^2.0.5
  screenshot: ^2.0.0
  hive_flutter: ^1.1.0
  path_provider:
  geolocator: 9.0.2
  permission_handler: any
  curved_navigation_bar: ^1.0.1
  image_picker: ^0.8.4+4
  provider: ^6.0.2
  flutter_svg: ^1.0.0
  geocoding: ^2.0.2

  fluttertoast: ^8.0.8
  flutter_native_splash:

  font_awesome_flutter: ^10.4.0

  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^9.3.2
  #  syncfusion_flutter_datagrid: ^20.3.52
  #  syncfusion_flutter_core: ^20.3.52
  syncfusion_flutter_datagrid: ^19.4.56
  syncfusion_flutter_core: ^19.4.56
  lottie: ^1.3.0
  flutter_countdown_timer: ^4.1.0
  back_button_interceptor: ^5.0.0
  flutter_image_compress: ^2.0.0
  #firebase_crashlytics: ^2.9.0

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/splash/
    - assets/icons/on_boarding/
    - assets/icons/auth/
    - assets/icons/auth/sign_up/
    - assets/icons/select_car/
    - assets/icons/My Account/
    - assets/icons/home/
    - assets/images/
    - assets/svg/
    - assets/icons/My Vehicle/
    - assets/
    - assets/icons/jobcard/
    - assets/language/
    - assets/icons/auth/addicon.png
  fonts:
    - family: Poppins1
      fonts:
        - asset: fonts/Poppins-Medium.ttf

    - family: Poppins2
      fonts:
        - asset: fonts/Poppins-Bold.ttf

    - family: Poppins4
      fonts:
        - asset: fonts/Poppins-SemiBoldItalic.ttf

    - family: Poppins3
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: Montserrat1
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family: Montserrat2
      fonts:
        - asset: fonts/Montserrat-Medium.ttf

    - family: OpenSans1
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

    - family: Montserrat3
      fonts:
        - asset: fonts/Poppins-SemiBoldItalic.ttf

    - family: IBM Plex Sans Arabic
      fonts:
        - asset: fonts/Arabic-Regular.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
